### ISSUE TITLE
🛑 Slack Alert Test Site is down

### ISSUE THREAD

**Issue by alex-bluetec** [Buddy-Technology/buddy-status#6]
In [`8ba9cf4`](https://github.com/Buddy-Technology/buddy-status/commit/8ba9cf48c22546b52c726d4c6f1c03e2b32183d1
), Slack Alert Test Site (http://qwiovnewc.com/) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by individual11** [comment]
What?
